%n=0:5;
%u=n>=0;
%a=1;
%f=0.1;
%x=a*sin(2*pi*f*n);
%y=u+x;
%z=u-x;
%subplot(2,2,1);stem(n,u);
%subplot(2,2,2);stem(n,x);
%subplot(2,2,3);stem(n,y);
%subplot(2,2,4);stem(n,z);
%grid on;

n=0:0.1:1;
a=2;
f=2;
x=a*sin(2*pi*f*n);
subplot(2,3,1);
stem(n,x,'b');
y=a*cos(2*pi*f*n);
subplot(2,3,2);
stem(n,x,'b');
u=x+y;
subplot(2,3,3);
stem(n,u,'b');
v=x-y;
subplot(2,3,4);
stem(n,v,'b');
w=x .* y;
subplot(2,3,5);
stem(n,w,'b');
p=x ./ y;
subplot(2,3,6);
stem(n,p,'b');
grid on;